import{a as i}from"./assets/vendor-0cb09735.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function r(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(o){if(o.ep)return;o.ep=!0;const n=r(o);fetch(o.href,n)}})();function S(){const e=document.querySelector(".toggle-theme");let t=document.documentElement;e.addEventListener("click",r=>{r.preventDefault(),t.hasAttribute("data-theme")?(t.removeAttribute("data-theme"),localStorage.removeItem("theme")):(t.setAttribute("data-theme","dark"),localStorage.setItem("theme","dark"))}),localStorage.getItem("theme")!==null&&t.setAttribute("data-theme","dark")}S();i.defaults.baseURL="https://books-backend.p.goit.global/books";const u={getCategoryList:async function(){try{return(await i.get("/category-list")).data}catch(e){console.log(e)}},getBestSellers:async function(){try{return(await i.get("/top-books")).data}catch(e){console.log(e)}},getCategory:async function(e){try{return(await i.get(`/category?category=${e}`)).data}catch(t){console.log(t)}},getBookDescription:async function(e){try{return(await i.get(`/${e}`)).data}catch(t){console.log(t)}}};function v(e,t){const r=document.querySelector(e),s=t.split(" "),o=s[s.length-1];s.pop(),t=s.join(" "),r.insertAdjacentHTML("afterbegin",`<h1 class="page-title">${t} <span class="page-title-highlight">${o}</span></h1>`)}function B({title:e,author:t,book_image:r}){return`<li class="book-category-item">
  <div class="book-category-card">
    <img class="book-category-image" src="${r}" alt="Book cover" width="180" />
    <div class="book-category-text">
      <h3 class = "book-title">
      ${e}</h3>
      <p class = "author-name"> ${t}</p>
    </div>
  </div>
</li>`}function h(e){const t=document.querySelector(".bestsellers-container");t.innerHTML="",v(".bestsellers-container","Best Sellers Books"),t.insertAdjacentHTML("beforeend",'<ul class="bestsellers-list"></ul>');const r=document.querySelector(".bestsellers-list"),s=e.map(({books:o,list_name:n})=>`
            <li class="bestsellers-item">
             <h2 class="bestsellers-category-title">${n}</h2>
                <ul class="bestsellers-books-list"> 
                    ${o.map(({book_image:a,title:c,author:l})=>B({book_image:a,title:c,author:l})).join(`
`)}
                </ul>
                <button class="bestsellers-btn" type="button data-category="${n}">See more</button>
            </li>`).join(`
`);r.insertAdjacentHTML("beforeend",s)}async function w(){try{const e=await u.getBestSellers();return h(e)}catch(e){console.error("Error fetching best sellers:",e)}}w();function C(e,t){const r=document.querySelector(e),s=t.split(" "),o=s[s.length-1];s.pop(),t=s.join(" "),r.insertAdjacentHTML("afterbegin",`<h1 class="page-title">${t} <span class="page-title-highlight">${o}</span></h1>`)}function $({title:e,author:t,book_image:r}){return`<li class="book-category-item">
  <div class="book-category-card">
    <img class="book-category-image" src="${r}" alt="Book cover" width="180" />
    <div class="book-category-text">
      <h3 class = "book-title">
      ${e}</h3>
      <p class = "author-name"> ${t}</p>
    </div>
  </div>
</li>`}function q(e,t){const r=document.querySelector(".bestsellers-container");r.innerHTML="",C(".bestsellers-container",t),r.insertAdjacentHTML("beforeend",'<ul class = "book-category-list"></ul>');const s=document.querySelector(".book-category-list"),o=e.map(({author:n,book_image:a,title:c,_id:l})=>$({author:n,book_image:a,title:c,_id:l})).join("");s.innerHTML=o}const g={categoryContainer:document.querySelector(".sidebar-category-container"),categoryList:document.querySelector(".sidebar-category-list"),allCategory:document.querySelector(".all-category")};function x(e){return e.map(r=>`<li class='sidebar-category-item' data-source="${r.list_name}">${r.list_name}</li>`).join("")}(async()=>{try{const e=await u.getCategoryList(),t=x(e);g.categoryList.insertAdjacentHTML("beforeend",t)}catch(e){console.log(e)}})();g.allCategory.addEventListener("click",async e=>{try{const t=await u.getBestSellers();h(t)}catch(t){console.log(t)}});g.categoryList.addEventListener("click",async e=>{if(e.target.classList.contains("sidebar-category-item")){const t=e.target.dataset.source;document.querySelectorAll(".sidebar-category-item").forEach(s=>{s.classList.remove("category-active")}),e.target.classList.add("category-active");try{if(!e.target.classList.contains("all-category")){const s=await u.getCategory(t);q(s,t)}}catch(s){console.log(s)}}});document.addEventListener("DOMContentLoaded",function(){});const f=new LocalStorage,y=f.getProducts();function E(){const e=document.getElementById("bookList");if(e.innerHTML="",y.length===0||!f){e.innerHTML=`
            <li>
                <picture>
                    <source srcset="../images/shopping-list/placeholder.webp" type="image/webp">
                    <source srcset="../images/shopping-list/placeholder.png" type="image/png">
                    <source srcset="../images/shopping-list/placeholder2x.webp" type="image/webp">
                    <source srcset="../images/shopping-list/placeholder2x.png" type="image/png">
                    <img src="../images/shopping-list/placeholder.png" alt="No Books Added">
                </picture>
            </li>`;return}y.forEach(t=>{const r=document.createElement("li");r.textContent=t,e.appendChild(r)})}E();let P=class{constructor(){this.keyName="shopping-list"}getProducts(){const t=localStorage.getItem(this.keyName);return t!==null?JSON.parse(t):[]}checkProduct(t){let r=this.getProducts(),s=r.findIndex(n=>n.id==t);const o={hasProd:!1,index:s,arrProd:r};return s!==-1&&(o.hasProd=!0),o}putProducts(t){let{hasProd:r,index:s,arrProd:o}=this.checkProduct(t.id);r!==!0?o.push(t):o.splice(s,1),localStorage.setItem(this.keyName,JSON.stringify(o))}};document.addEventListener("DOMContentLoaded",function(){const e=document.getElementById("modal"),t=document.querySelector(".modal-close"),r=document.querySelector(".modal-add-to-cart"),s=new P;function o(){e.style.display="none",document.body.style.overflow="auto"}t.addEventListener("click",o),e.addEventListener("click",function(c){c.target===e&&o()}),document.addEventListener("keydown",function(c){c.key==="Escape"&&o()});function n(c){const l=e.querySelector(".book-cover"),b=e.querySelector(".book-title"),k=e.querySelector(".author"),L=e.querySelector(".description"),p=e.querySelector(".links");l.src=c.coverImageUrl,b.textContent=c.title,k.textContent="Author: "+c.author,L.textContent=c.description,p.innerHTML="",c.links.forEach(function(m){const d=document.createElement("a");d.href=m.url,d.textContent=m.name,d.target="_blank",p.appendChild(d)}),s.checkProduct(c.id).hasProd?r.textContent="Remove from Shopping List":r.textContent="Add to Shopping List"}n({id:1,coverImageUrl:"https://example.com/book-cover.jpg",title:"Example Book Title",author:"John Doe",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",links:[{name:"Amazon",url:"https://www.amazon.com"},{name:"Apple Books",url:"https://books.apple.com"}]})});document.querySelector(".home-page");
//# sourceMappingURL=commonHelpers.js.map
