import{a as i}from"./assets/vendor-0cb09735.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(o){if(o.ep)return;o.ep=!0;const r=n(o);fetch(o.href,r)}})();function C(){const t=document.querySelector(".toggle-theme");let e=document.documentElement;t.addEventListener("click",n=>{n.preventDefault(),e.hasAttribute("data-theme")?(e.removeAttribute("data-theme"),localStorage.removeItem("theme")):(e.setAttribute("data-theme","dark"),localStorage.setItem("theme","dark"))}),localStorage.getItem("theme")!==null&&e.setAttribute("data-theme","dark")}C();i.defaults.baseURL="https://books-backend.p.goit.global/books";const d={getCategoryList:async function(){try{return(await i.get("/category-list")).data}catch(t){console.log(t)}},getBestSellers:async function(){try{return(await i.get("/top-books")).data}catch(t){console.log(t)}},getCategory:async function(t){try{return(await i.get(`/category?category=${t}`)).data}catch(e){console.log(e)}},getBookDescription:async function(t){try{return(await i.get(`/${t}`)).data}catch(e){console.log(e)}}};function q(t,e){const n=document.querySelector(t),s=e.split(" "),o=s[s.length-1];s.pop(),e=s.join(" "),n.insertAdjacentHTML("afterbegin",`<h1 class="page-title">${e} <span class="page-title-highlight">${o}</span></h1>`)}function M({title:t,author:e,book_image:n,_id:s}){return`<li class="book-category-item" data-id="${s}">
    <div class = "img-cover">
      <img class="book-category-image" src="${n}" alt="Book cover" width="335"  /> 
      <p class="overlay-text">quick view</p>
      </div>
        <div class="book-category-text">
      <h3 class = "book-title">
      ${t}</h3>
      <p class = "author-name"> ${e}</p>
    </div>
 </li>`}function L(t){const e=document.querySelector(".bestsellers-container");e.innerHTML="",q(".bestsellers-container","Best Sellers Books"),e.insertAdjacentHTML("beforeend",'<ul class="bestsellers-list"></ul>');const n=document.querySelector(".bestsellers-list"),s=t.map(({books:r,list_name:a})=>`<li class="bestsellers-item">
              <h2 class="bestsellers-category-title">${a}</h2>
              <ul class="bestsellers-books-list"> 
                ${r.map(({title:l,author:u,book_image:c,_id:m})=>M({title:l,author:u,book_image:c,_id:m})).join(`
`)}
              </ul>
              <button class="bestsellers-btn" type="button" data-category="${a}">See more</button>
            </li>`).join(`
`);n.insertAdjacentHTML("beforeend",s),document.querySelector(".bestsellers-list").addEventListener("click",T)}async function x(){try{const t=await d.getBestSellers();return L(t)}catch(t){console.error("Error fetching best sellers:",t)}}x();async function T(t){try{if(t.target.nodeName!=="BUTTON")return;let e=t.target.dataset.category;const n=document.querySelector(".sidebar-category-item");document.querySelectorAll(".sidebar-category-item").forEach(r=>{r.dataset.source===e&&(n.classList.remove("category-active"),r.classList.add("category-active"))});const o=await d.getCategory(e);k(o,e)}catch(e){console.log("Error fetching modal:",e)}}function I(t,e){const n=document.querySelector(t),s=e.split(" "),o=s[s.length-1];s.pop(),e=s.join(" "),n.insertAdjacentHTML("afterbegin",`<h1 class="page-title">${e} <span class="page-title-highlight">${o}</span></h1>`)}function $({title:t,author:e,book_image:n,_id:s}){return`<li class="book-category-item" data-id="${s}">
    <div class = "img-cover">
      <img class="book-category-image" src="${n}" alt="Book cover" width="335"  /> 
      <p class="overlay-text">quick view</p>
      </div>
        <div class="book-category-text">
      <h3 class = "book-title">
      ${t}</h3>
      <p class = "author-name"> ${e}</p>
    </div>
 </li>`}function k(t,e){const n=document.querySelector(".bestsellers-container");n.innerHTML="",I(".bestsellers-container",e),n.insertAdjacentHTML("beforeend",'<ul class = "book-category-list"></ul>');const s=document.querySelector(".book-category-list"),o=t.map(({author:r,book_image:a,title:l,_id:u})=>$({author:r,book_image:a,title:l,_id:u})).join("");s.innerHTML=o,s.addEventListener("click",onClickBook)}const h={categoryContainer:document.querySelector(".sidebar-category-container"),categoryList:document.querySelector(".sidebar-category-list"),allCategory:document.querySelector(".all-category")};function A(t){return t.map(n=>`<li class='sidebar-category-item' data-source="${n.list_name}">${n.list_name}</li>`).join("")}(async()=>{try{const t=await d.getCategoryList(),e=A(t);h.categoryList.insertAdjacentHTML("beforeend",e)}catch(t){console.log(t)}})();h.allCategory.addEventListener("click",async t=>{try{const e=await d.getBestSellers();L(e)}catch(e){console.log(e)}});h.categoryList.addEventListener("click",async t=>{if(t.target.classList.contains("sidebar-category-item")){const e=t.target.dataset.source;document.querySelectorAll(".sidebar-category-item").forEach(s=>{s.classList.remove("category-active")}),t.target.classList.add("category-active");try{if(!t.target.classList.contains("all-category")){const s=await d.getCategory(e);k(s,e)}}catch(s){console.log(s)}}});document.addEventListener("DOMContentLoaded",function(){});document.addEventListener("DOMContentLoaded",function(){var t=document.getElementById("fundList"),e=t.getElementsByClassName("fund-item"),n=document.querySelector(".fund-btn");function s(){for(var r=0;r<e.length;r++)e[r].style.display="none"}s();for(var o=0;o<6;o++)e[o].style.display="block";n.addEventListener("click",function(){for(var r=0;r<3;r++)e[r].style.display!=="none"&&(e[r].style.display="none");for(var r=6;r<12;r++)e[r]&&(e[r].style.display="block")})});class v{constructor(){this.keyName="shopping-list"}getProducts(){const e=localStorage.getItem(this.keyName);return e!==null?JSON.parse(e):[]}checkProduct(e){let n=this.getProducts(),s=n.findIndex(r=>r.id==e);const o={hasProd:!1,index:s,arrProd:n};return s!==-1&&(o.hasProd=!0),o}putProducts(e){let{hasProd:n,index:s,arrProd:o}=this.checkProduct(e.id);n!==!0?o.push(e):o.splice(s,1),localStorage.setItem(this.keyName,JSON.stringify(o))}}const S=new v,b=S.getProducts();function P(){const t=document.getElementById("bookList");if(t.innerHTML="",b.length===0||!S){t.innerHTML=`
            <li>
                <picture>
                    <source srcset="../images/shopping-list/placeholder.webp" type="image/webp">
                    <source srcset="../images/shopping-list/placeholder.png" type="image/png">
                    <source srcset="../images/shopping-list/placeholder2x.webp" type="image/webp">
                    <source srcset="../images/shopping-list/placeholder2x.png" type="image/png">
                    <img src="../images/shopping-list/placeholder.png" alt="No Books Added">
                </picture>
            </li>`;return}b.forEach(e=>{const n=document.createElement("li");n.textContent=e,t.appendChild(n)})}P();(()=>{const t=document.querySelector(".js-menu-container"),e=document.querySelector(".btn-menu"),n=document.querySelector(".js-close-menu"),s=()=>{const o=e.getAttribute("aria-expanded")==="true"||!1;e.setAttribute("aria-expanded",!o),t.classList.toggle("is-open");const r=o?"enableBodyScroll":"disableBodyScroll";bodyScrollLock[r](document.body)};e.addEventListener("click",s),n.addEventListener("click",s),window.matchMedia("(min-width: 768px)").addEventListener("change",o=>{o.matches&&(t.classList.remove("is-open"),e.setAttribute("aria-expanded",!1),bodyScrollLock.enableBodyScroll(document.body))})})();document.addEventListener("DOMContentLoaded",function(){const t=document.getElementById("modal"),e=document.querySelector(".modal-close"),n=document.querySelector(".modal-add-to-cart"),s=document.querySelector(".logo-amazon"),o=document.querySelector(".logo-apple"),r=new v;function a(){t.style.display="none",document.body.style.overflow="auto",document.documentElement.style.overflow="auto"}e.addEventListener("click",a),t.addEventListener("click",function(c){c.target===t&&a()}),document.addEventListener("keydown",function(c){c.key==="Escape"&&a()}),s.addEventListener("click",function(c){c.preventDefault(),window.open(this.href,"_blank")}),o.addEventListener("click",function(c){c.preventDefault(),window.open(this.href,"_blank")});function l(c){const m=t.querySelector(".book-cover"),w=t.querySelector(".book-title"),E=t.querySelector(".author"),B=t.querySelector(".description"),f=t.querySelector(".links");m.src=c.coverImageUrl,w.textContent=c.title,E.textContent="Author: "+c.author,B.textContent=c.description,f.innerHTML="",c.links.forEach(function(p){const g=document.createElement("a");g.href=p.url,g.target="_blank";const y=document.createElement("img");y.src=p.logoUrl,y.alt=p.name,g.appendChild(y),f.appendChild(g)}),r.checkProduct(c.id).hasProd?n.textContent="Remove from Shopping List":n.textContent="Add to Shopping List"}l({id:1,coverImageUrl:"https://example.com/book-cover.jpg",title:"Example Book Title",author:"John Doe",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",links:[{logoUrl:"/src/images/pop-up/amazon.svg",url:"https://www.amazon.com"},{logoUrl:"/src/images/pop-up/apple.svg",url:"https://books.apple.com"}]})});document.addEventListener("DOMContentLoaded",function(){const t=document.createElement("button");t.classList.add("scroll-button"),t.textContent="^",document.body.appendChild(t);function e(){window.scrollTo({top:0,behavior:"smooth"})}t.addEventListener("click",e),window.addEventListener("scroll",function(){window.scrollY>100?t.classList.add("show"):t.classList.remove("show")})});document.querySelector(".home-page");
//# sourceMappingURL=commonHelpers.js.map
