import{a as l}from"./assets/vendor-0cb09735.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();function h(){const e=document.querySelector(".toggle-theme");let o=document.documentElement;e.addEventListener("click",n=>{n.preventDefault(),o.hasAttribute("data-theme")?(o.removeAttribute("data-theme"),localStorage.removeItem("theme")):(o.setAttribute("data-theme","dark"),localStorage.setItem("theme","dark"))}),localStorage.getItem("theme")!==null&&o.setAttribute("data-theme","dark")}h();l.defaults.baseURL="https://books-backend.p.goit.global/books";const d={getCategoryList:async function(){try{return(await l.get("/category-list")).data}catch(e){console.log(e)}},getBestSellers:async function(){try{return(await l.get("/top-books")).data}catch(e){console.log(e)}}},f={categoryContainer:document.querySelector(".category-container"),categoryList:document.querySelector(".category-list"),categoryItem:document.querySelector(".category-item"),allCategory:document.querySelector(".all-category")};function S(e){return e.map(n=>`<li class='category-item'>${n.list_name}</li>`).join("")}(async()=>{try{const e=await d.getCategoryList(),o=S(e);f.categoryList.insertAdjacentHTML("beforeend",o)}catch(e){console.log(e)}})();const b=document.querySelector(".categories-books-list"),k=async()=>{try{const o=(await d.getBestSellers()).map(({books:n,list_name:c})=>`<li class="categories-item">${c}
                <ul class="categories-books-list"> 
                    ${n.map(({book_image:t,title:r,author:s})=>`<li class="categories-item">
                            <img class="categories-img" src='${t}' alt="" />
                            <h3 class="categories-book-title">${r}</h3>
                            <p class="categories-book-author">${s}</p>
                        </li>`).join(`
`)}
                </ul>
                <button class="categories-btn" type="button">See more</button>
            </li>`).join(`
`);b.insertAdjacentHTML("beforeend",o)}catch(e){console.error("Error fetching best sellers:",e)}};k();document.addEventListener("DOMContentLoaded",function(){const e=document.getElementById("modal"),o=document.querySelector(".close"),n=document.querySelector(".add-to-cart");function c(){e.style.display="none",document.body.style.overflow="auto"}o.addEventListener("click",c),e.addEventListener("click",function(s){s.target===e&&c()}),document.addEventListener("keydown",function(s){s.key==="Escape"&&c()});function t(s){const m=e.querySelector(".book-cover"),g=e.querySelector(".book-title"),p=e.querySelector(".author"),y=e.querySelector(".description"),u=e.querySelector(".links");m.src=s.coverImageUrl,g.textContent=s.title,p.textContent="Author: "+s.author,y.textContent=s.description,u.innerHTML="",s.links.forEach(function(a){const i=document.createElement("a");i.href=a.url,i.textContent=a.name,i.target="_blank",u.appendChild(i)}),(JSON.parse(localStorage.getItem("shoppingList"))||[]).some(function(a){return a.id===s.id})?n.textContent="Remove from Shopping List":n.textContent="Add to Shopping List"}t({id:1,coverImageUrl:"https://example.com/book-cover.jpg",title:"Example Book Title",author:"John Doe",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",links:[{name:"Amazon",url:"https://www.amazon.com"},{name:"Apple Books",url:"https://books.apple.com"}]})});class L{constructor(){this.keyName="shopping-list"}getProducts(){const o=localStorage.getItem(this.keyName);return o!==null?JSON.parse(o):[]}checkProduct(o){let n=this.getProducts(),c=n.findIndex(r=>r.id==o);const t={hasProd:!1,index:c,arrProd:n};return c!==-1&&(t.hasProd=!0),t}putProducts(o){let{hasProd:n,index:c,arrProd:t}=this.checkProduct(o.id);n!==!0?t.push(o):t.splice(c,1),localStorage.setItem(this.keyName,JSON.stringify(t))}}const v=new L,P=v.getProducts();console.log(P);
//# sourceMappingURL=commonHelpers.js.map
